import * as fs from 'fs';
import * as path from 'path';

export interface ReviewIssue {
    category: 'Domain' | 'Logic' | 'Page';
    location: string;
    message: string;
    recommendation?: string; // 추천 해결책 추가
    severity: 'Warning' | 'Error';
}

export interface CommitInfo {
    appName: string;
    branch: string;
    author: string;
    date: Date;
    revId: string;
    message: string;
    appId: string;
}

export async function generateReport(commitInfo: CommitInfo, issues: ReviewIssue[]) {
    // 1. 프로젝트명과 브랜치명을 포함한 경로 설정 (appName이 없을 경우 대비)
    const safeAppName = commitInfo.appName || "UnknownApp";
    const safeBranchName = commitInfo.branch || "main";
    const reportDir = path.join(process.cwd(), 'reports', safeAppName, safeBranchName);
    
    if (!fs.existsSync(reportDir)) {
        fs.mkdirSync(reportDir, { recursive: true });
    }

    // 2. 파일명 단순화 및 시간 추가 (이력 보존)
    const now = new Date();
    const timestamp = now.getFullYear().toString() + 
                      (now.getMonth() + 1).toString().padStart(2, '0') + 
                      now.getDate().toString().padStart(2, '0') + "_" +
                      now.getHours().toString().padStart(2, '0') + 
                      now.getMinutes().toString().padStart(2, '0');
    
    const fileName = `${timestamp}_rev${commitInfo.revId}.md`;
    const filePath = path.join(reportDir, fileName);

    // 3. 커밋 주소 생성 (Mendix Team Server URL 추측 - 일반적으로 Sprintr URL 기반)
    const commitUrl = `https://pivotal.mendixcloud.com/link/app/${commitInfo.appId}/vcs/revision/${commitInfo.revId}`;

    // 4. 마크다운 내용 구성
    let content = `# 🤖 Mendix Core Architecture & Performance Report\n\n`;
    
    content += `## 📌 Project Context\n`;
    content += `- **Branch:** \`${commitInfo.branch}\`\n`;
    content += `- **Commit:** [${commitInfo.revId.substring(0, 8)}](${commitUrl})\n`;
    content += `- **Author:** ${commitInfo.author}\n`;
    content += `- **Review Date:** ${new Date().toLocaleString()}\n\n`;

    content += `## 🎯 핵심 성능 및 아키텍처 지표 (KPI)\n`;
    content += `| Metric | Target | Status | Result |\n`;
    content += `| :--- | :--- | :--- | :--- |\n`;
    
    const criticalIssues = issues.filter(i => i.severity === 'Error').length;
    const logicIssues = issues.filter(i => i.category === 'Logic' && i.message.includes('복잡도')).length;
    const dbIssues = issues.filter(i => i.message.includes('루프 내 DB')).length;

    content += `| **치명적 오류 (Critical)** | 0건 | ${criticalIssues === 0 ? '✅ Pass' : '❌ Fail'} | ${criticalIssues}건 발견 |\n`;
    content += `| **로직 복잡도 (Complexity)** | < 20 actions | ${logicIssues === 0 ? '✅ Pass' : '⚠️ Warning'} | ${logicIssues}개 과부화 |\n`;
    content += `| **성능 병목 (Bottleneck)** | 0건 | ${dbIssues === 0 ? '✅ Pass' : '❌ Fail'} | ${dbIssues}건 발견 |\n\n`;

    content += `## 📊 Summary\n`;
    content += `- **Total Issues Found:** ${issues.length}\n`;
    content += `- **Critical Errors:** ${issues.filter(i => i.severity === 'Error').length}\n`;
    content += `- **General Warnings:** ${issues.filter(i => i.severity === 'Warning').length}\n\n`;

    content += `## 🔍 상세 분석 리스트\n\n`;
    
    if (issues.length === 0) {
        content += `### 🎉 분석 결과: 아주 훌륭합니다!\n`;
        content += `현재 브랜치의 모델에서 치명적인 설계 오류나 성능 저하 요인이 발견되지 않았습니다. 아키텍처 가이드라인을 아주 잘 준수하고 있습니다. 👍\n`;
    } else {
        content += `| Category | Location | Message | Recommendation | Severity |\n`;
        content += `| :--- | :--- | :--- | :--- | :--- |\n`;
        issues.sort((a, b) => a.severity === 'Error' ? -1 : 1).forEach(issue => {
            content += `| ${issue.category} | \`${issue.location}\` | ${issue.message} | ${issue.recommendation || '-'} | ${issue.severity === 'Error' ? '🔴 **Critical**' : '⚠️ Warning'} |\n`;
        });
    }

    content += `\n---\n*Generated by Mendix Code Reviewer Bot*`;

    // 5. 파일 저장
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`\n📄 보고서가 생성되었습니다: ${filePath}`);
    return filePath;
}
